### ISSUE TITLE
TypeError: Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by okaiyong** [jacob-meacham/angular-notification-icons#1]
I followed the usage section in read.md and manage to get the basic notification works. 
However, I got this error from my browser console which I can find a good explanation to rectify it. 

May I know which version of angular.js and angular.animate.js you are using?

**Comment by jacob-meacham** [comment]
I've tested everything explicitly with angular 1.3.15 and angular-animate 1.3.15. What version of angular are you using, and do you have a code snippet I could take a look at?

**Comment by okaiyong** [comment]
Thanks. Pardon me as i am new to coding. I was using a old version but just fixed it with a newer version. Using 1.3.16. 

By the way I tried running your demoworkspace but the envelope icon does not show up. Do u know any fiddle that helps? Appreciate much.

Sent from Samsung Mobile

-------- Original message --------

**Comment by jacob-meacham** [comment]
No problem! What version of angular were you using that didn't work? I'd like to update the readme with that information.

When you say you tried running the demo, what did you do? I cloned the repo fresh and ran gulp serve, and everything showed up as expected

**Comment by okaiyong** [comment]
I was using version 1.3.9 of angular-animate.jmin.js. After I change to version 1.4.2, it works. As for angular.js, I am using 1.3.16. 
I downloaded the codes in zip, unzipped and run the index.html using firefox. I checked the lib, css 's path but the icon doesn't show up. 
Thanks.

Date: Sun, 21 Jun 2015 21:57:07 -0700

**Comment by jacob-meacham** [comment]
Thanks for sending me the versions!

That makes sense, because the demo app uses special gulp injection to run. You'll want to do npm install and then gulp serve. If you want to just run without doing anything special, check out the gh-pages branch.

I'll update the readme to make it more clear how to run the demo app. Thanks!
