### ISSUE TITLE
Display the counter when count is <= 0

### ISSUE THREAD

**Issue by untemps** [jacob-meacham/angular-notification-icons#2]
Hi,
Great work!
One little feature is missing that prevents me from using the directive for now: could you introduce a new property to let display the counter even if the count is <= 0?
Thanks.
Vincent.

**Comment by jacob-meacham** [comment]
Yeah, that seems reasonable!

**Comment by jacob-meacham** [comment]
Fixed in 0.4.2. Thanks!

**Comment by untemps** [comment]
Nice! Thank you.
