### ISSUE TITLE
TypeError: element.parent is not a function

### ISSUE THREAD

**Issue by ayobuenavista** [jacob-meacham/angular-notification-icons#3]
TypeError: element.parent is not a function
    at queueAnimation (angular-animate.js:2237)
    at Object.push (angular-animate.js:2189)
    at Object.addClass (angular.js:5283)
    at handleAnimation (angular-notification-icons.js:42)
    at appear (angular-notification-icons.js:56)
    at Object.fn (angular-notification-icons.js:74)
    at Scope.$digest (angular.js:15826)
    at Scope.$apply (angular.js:16097)
    at done (angular.js:10546)
    at completeRequest (angular.js:10744)

Notification icon appears but animations don't work.
This error is present with angular 1.4.7, angular-animate 1.4.7, angular-notification-icons 0.4.2

**Comment by jacob-meacham** [comment]
Thanks for reporting! I'll take a look at it tonight or tomorrow.

**Comment by jacob-meacham** [comment]
I've was able to switch over the example app (http://jemonjam.com/angular-notification-icons/) using the appropriate resolutions. Can you try out develop ("angular-notification-icons": "git://github.com/jacob-meacham/angular-notification-icons#develop") and let me know if that fixes it? If it does, I'll cut a 0.4.3.

Thanks!

**Comment by ayobuenavista** [comment]
Thanks for looking into this. Unfortunately, I still get the same error. Which doesn't make sense to me because I just checked your demo app, and it's also using the same Angular versions as mine.

Now, on another note, I tried cloning your repo (develop branch) and I tried running it to trace and see if anything is wrong with mine. Or if some module is interfering. But I couldn't run your demo app. I get this error:

Uncaught Error: [$injector:modulerr] Failed to instantiate module angular-notification-icons.demo due to:
Error: [$injector:modulerr] Failed to instantiate module ngAnimate due to:
Error: [$injector:nomod] Module 'ngAnimate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=ngAnimate
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:1986:17
    (...)

I'm fairly new to Angular, so forgive me if I did something wrong. But here's what I did to try to run your app.
1) git clone https://github.com/jacob-meacham/angular-notification-icons.git -b develop
2) cd to project then, gulp build
3) gulp serve

When I visit the app, I get the error above. I checked your app.js, and ngAnimate is there, so I'm not sure what's wrong. All this is being done in Ubuntu 12.04.

If you need any additional information, I'd be glad to get them for you.

**Comment by jacob-meacham** [comment]
You'll need to run npm install and bower install first, before you can run gulp serve.

Is there any chance you can share your repo or a minimal working repro with me? That would make things a lot easier to debug

**Comment by ayobuenavista** [comment]
Hi again.

I was able to run your demo app successfully, and it works as expected. I still can't seem to trace what the error is on my app.

I've set up a simple repo for you. Sorry if it looks a bit messy since I had to strip out some internally-made packages and modules. We use our own custom generator. I just copy pasted stuff from your html and controller to put some content on the repo. I hope that the repo would give enough information though.

https://github.com/lindqvust/notification-test

**Comment by jacob-meacham** [comment]
Alright, I figured it out - thanks for the great repro!

The issue is a jqLite vs jquery difference (all of my tests have used jquery). I'll have a fix out shortly.

**Comment by jacob-meacham** [comment]
0.4.3 has been released, and should fix this issue. Thanks!

**Comment by ayobuenavista** [comment]
I can confirm that the fix works. Awesome!

Thanks for the great help!
