### ISSUE TITLE
Function request : Popover dialog box

### ISSUE THREAD

**Issue by wrjanan** [jacob-meacham/angular-notification-icons#4]
Thank you Jacob for sharing this module, it is easy to implement and works great..!

I will love for it to have a popover dialog / onclick dialog
- to have onclick dialog show

**Comment by wrjanan** [comment]
managed to edit the angular-notification-icons.js file to add on a mouseover attribute to the template script, so far the icon becomes clickable with an attached custom function. 

I have a few questions to ask if you will share your expertise it will be perfect :)
plan to edit the html file to add in a block of html code to show a popover
`<div id="notificationPopover">`
`<md-list>`
                     `<md-subheader class="md-no-sticky">Notifications</md-subheader>`
                      `<md-list-item ng-repeat="notificationItem in notificationsData.data.notifications">`
                    `<img alt="{{ ::notificationItem }}" ng-src="{{ ::notificationItem.imageUrl }}" class="md-avatar" />`
                    `<p>{{ ::notificationItem.type }}</p>`
                     `</md-list-item>`
                    `<md-button ui-sref="profile.notifications">See all</md-button>`
                    `</md-list>`
`</div>`

is this something that you would recommend if you were to implement such a popover dialog..? to edit the templateCache and have the controller to connect the scope attributes to a API call for attribute data

**Comment by jacob-meacham** [comment]
Hi wrjanan - sorry for the long delay (I was out of the country)

At first glance, this seems like a reasonable way to go. Let me know if you have any other questions!
