### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined error.

### ISSUE THREAD

**Issue by AyanSaha** [jacob-meacham/angular-notification-icons#5]

**Comment by jacob-meacham** [comment]
Hi @AyanSaha can you provide a few more details? What version of angular are you using, and what version of angular-notification-icons? Also, do you have the stack trace?

**Comment by AyanSaha** [comment]
I am using  AngularJS v1.2.13 and the latest build  of angular-notifications-icons

**Comment by jacob-meacham** [comment]
That's a really old version of angular! This module hasn't been tested against anything under 1.3.0, but I can reproduce your issue. I noodled around for a while, but it's not a simple task to fix, and makes the code strictly worse, so I don't want to support it in the mainline. If you want to try fixing it yourself in a fork, I think at least these things will be necessary:
1. Fixing up controllerAs, which isn't supported in 1.2. This means removing `notification.___` from the directive template
2. Fixing up handleAnimation to use the old $animate.addClass functionality. I think it should look like:

```
$animate.addClass(self.$element, animationClass, function() {
     self.$element.removeClass(animationClass);
     return $q.when(true);
});
```
1. Figure out why $watch isn't getting called. As far as I can tell, a $watch with a function as the first parameter should work, but $watch is not getting called, and I stopped digging before I got to the bottom of this.

Let me know if you need any assistance - I'm happy to give pointers!

**Comment by AyanSaha** [comment]
Thanks buddy i updated my angular version to 1.3 and now it is working fine
