### ISSUE TITLE
Add to NPM registry

### ISSUE THREAD

**Issue by benjamincharity** [jacob-meacham/angular-notification-icons#6]
Removing Bower from our projects at work.. would love to be able to `npm install angular-notification-icons`

**Comment by jacob-meacham** [comment]
Definitely! I'll take a look at converting this over to Webpack tonight

**Comment by thachp** [comment]
Awesome! What is the update on this?

**Comment by jacob-meacham** [comment]
I got busy at work getting a deliverable out, but my hope is to wrap this up today or tomorrow (I took the opportunity to also convert the source to es6 and radically simplify the gulp build)

**Comment by jacob-meacham** [comment]
Published! https://www.npmjs.com/package/angular-notification-icons

This should work statically (ie just adding script tags to your html), or via an import/require() in webpack/rollup/browserify. Let me know if this doesn't work for you!
